/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkdemo_test4_TestJni4 */

#ifndef _Included_com_example_ndkdemo_test4_TestJni4
#define _Included_com_example_ndkdemo_test4_TestJni4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkdemo_test4_TestJni4
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ndkdemo_test4_TestJni4_getVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
