/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkdemo_test3_TestJni3 */

#ifndef _Included_com_example_ndkdemo_test3_TestJni3
#define _Included_com_example_ndkdemo_test3_TestJni3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkdemo_test3_TestJni3
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkdemo_test3_TestJni3_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndkdemo_test3_TestJni3
 * Method:    callbackHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkdemo_test3_TestJni3_callbackHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndkdemo_test3_TestJni3
 * Method:    callbackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkdemo_test3_TestJni3_callbackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndkdemo_test3_TestJni3
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkdemo_test3_TestJni3_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
