/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkdemo_test2_TestJni2 */

#ifndef _Included_com_example_ndkdemo_test2_TestJni2
#define _Included_com_example_ndkdemo_test2_TestJni2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkdemo_test2_TestJni2
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndkdemo_test2_TestJni2_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_ndkdemo_test2_TestJni2
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndkdemo_test2_TestJni2_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_ndkdemo_test2_TestJni2
 * Method:    increaseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_ndkdemo_test2_TestJni2_increaseArrayEles
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_ndkdemo_test2_TestJni2
 * Method:    checkPwd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndkdemo_test2_TestJni2_checkPwd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
